package commons

const (
	SYSINFO             = "sysinfo"
	SYSINFO_STATUS      = "sysinfo.status"
	SYSINFO_CREATEDAT   = "sysinfo.createdat"
	SYSINFO_MODIFIEDAT  = "sysinfo.modifiedat"
	APPS                = "apps"
	APPS_I              = "apps.%d"
	APPS_I_ID           = "apps.%d.id"
	APPS_ID             = "apps.id"
	APPS_I_OBJTYPE      = "apps.%d.objType"
	APPS_OBJTYPE        = "apps.objType"
	APPS_I_NAME         = "apps.%d.name"
	APPS_NAME           = "apps.name"
	APPS_I_DESCRIPTION  = "apps.%d.description"
	APPS_DESCRIPTION    = "apps.description"
	APPS_I_PATH         = "apps.%d.path"
	APPS_PATH           = "apps.path"
	APPS_I_ROLEREQUIRED = "apps.%d.roleRequired"
	APPS_ROLEREQUIRED   = "apps.roleRequired"
	ROLES               = "roles"
	ROLES_I             = "roles.%d"
	ROLES_I_DOMAIN      = "roles.%d.domain"
	ROLES_DOMAIN        = "roles.domain"
	ROLES_I_SITE        = "roles.%d.site"
	ROLES_SITE          = "roles.site"
	ROLES_I_APPS        = "roles.%d.apps"
	ROLES_APPS          = "roles.apps"
)
